name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR file
        run: |
          mvn clean package -DskipTests
          ls -lh target/*.jar  # Debugging output

      - name: Build and push Docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t "${{ secrets.DOCKER_USERNAME }}/random-number-generator:latest" .
          docker push "${{ secrets.DOCKER_USERNAME }}/random-number-generator:latest"

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Wait for build job to finish

    steps:
      - name: Deploy to VPS via SSH using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker pull "${{ secrets.DOCKER_USERNAME }}/random-number-generator:latest"
            docker stop springboot-container || true
            docker rm springboot-container || true
            docker run -d --name springboot-container -p 8089:8089 "${{ secrets.DOCKER_USERNAME }}/random-number-generator:latest"
